# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

presubmits:

  #########################################################
  # lint, build and test
  #########################################################
  - name: pre-kubermatic-lint
    run_if_changed: ".*.go"
    decorate: true
    clone_uri: "git@github.com:kubermatic/benchmate.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
      - image: golangci/golangci-lint:v1.42.1
        command:
        - make
        args:
        - lint
        resources:
          requests:
            memory: 500Mi
            cpu: 2
          
  - name: pre-benchmate-build-test
    run_if_changed: ".*.go"
    decorate: true
    clone_uri: "git@github.com:kubermatic/benchmate.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
      - image: quay.io/kubermatic/build:go-1.17-node-16-5
        command:
        - make
        args:
        - build
        - test
        resources:
          requests:
            memory: 500Mi
            cpu: 2
            